# Rifle's Chair plugin by Rifle D. Luffy
# Version 4.5
# #=============[Seat Configuration]=============##
# seating-position: The exact positions of where the armorstand spawns; default 0.5,0.25,0.5
# exit-seat-where-facing: Exit the seat where you are facing.
# max-distance: the maximum distance a player can be in order to sit on the seat
# max-item-count-to-sit: If they have more than this, they can't sit. Example: >10 dirt cannot sit
# set it to -1 to cancel.
# require-signs-at-end: checks for signs at the end of a seat; false by default
# priority-on-if-has-perm: if they have the perm rfchairs.priority, they will be allowed to replace users
# allow-trap-door-chairs: allows the player to sit on a chair that resembles a "throne"
# require-empty-hand: players must have no items in their hand to sit
# #=============[When Damaged By an Entity]=============##
# eject-player-on-damage: Should it eject players of their seats when damaged?
# minimum-eject-damage: The minumum damage needed to toss a player out of their seat
# face-attacker-when-ejected: Should the attacked face the attacker when hit out of their seat?
# #=============[Tossing players out of seats]=============##
# toss-player: will the players be tossed when they 
# toss-velocity: the velocity of the attacked when knocked out of their seat
# scale-toss-velocity: whether or not the toss-velocity will increase if attacker is running
# velocity-scale-factor: how much the velocity is multiplied if attacker is running
# #=============[Customization]=============##
# regen-when-sitting: players regenerate when sitting on chairs
# regen-potency: the regen potion effect level where 0 is level 1
# allow-custom-messages: allow the use of custom messages when events are triggered
# allowed-chairs: The chairs that people are allowed to sit on
seating-position: 0.5,0.25,0.5
disable-update-message-if-on-latest: false
disable-update-messages: false
exit-seat-where-facing: false
allow-trap-door-chairs: true
require-empty-hand: false
max-distance: 2
max-item-count-to-sit: -1
require-signs-at-end: false
eject-player-on-damage: false
minimum-eject-damage: 2
face-attacker-when-ejected: false
toss-player: false
toss-velocity: 0.5
scale-toss-velocity: true
velocity-scale-factor: 2
regen-when-sitting: true
regen-potency: 0
allow-custom-messages: false
priority-on-if-has-perm: true
allowed-chairs:
  - ACACIA_STAIRS
  - BIRCH_STAIRS
  - BRICK_STAIRS
  - COBBLESTONE_STAIRS
  - DARK_OAK_STAIRS
  - DARK_PRISMARINE_STAIRS
  - JUNGLE_STAIRS
  - NETHER_BRICK_STAIRS
  - OAK_STAIRS
  - PRISMARINE_BRICK_STAIRS
  - PRISMARINE_STAIRS
  - PURPUR_STAIRS
  - QUARTZ_STAIRS
  - RED_SANDSTONE_STAIRS
  - SANDSTONE_STAIRS 
  - SPRUCE_STAIRS
  - WOOD_STAIRS
  - STONE_BRICK_STAIRS
  - ACACIA_SLAB
  - BIRCH_SLAB
  - BRICK_SLAB
  - COBBLESTONE_SLAB
  - DARK_OAK_SLAB
  - DARK_PRISMARINE_SLAB
  - JUNGLE_SLAB
  - NETHER_BRICK_SLAB
  - OAK_SLAB
  - PETRIFIED_OAK_SLAB
  - PRISMARINE_BRICK_SLAB
  - PRISMARINE_SLAB
  - PURPUR_SLAB 
  - QUARTZ_SLAB
  - RED_SANDSTONE_SLAB
  - SANDSTONE_SLAB
  - SPRUCE_SLAB
  - STONE_BRICK_SLAB
  - STONE_SLAB
  - BLACK_CARPET
  - BLUE_CARPET
  - BROWN_CARPET
  - CYAN_CARPET
  - GRAY_CARPET
  - GREEN_CARPET
  - LIGHT_BLUE_CARPET
  - LIGHT_GRAY_CARPET
  - LIME_CARPET
  - MAGENTA_CARPET
  - ORANGE_CARPET
  - PINK_CARPET
  - PURPLE_CARPET
  - RED_CARPET
  - WHITE_CARPET
  - YELLOW_CARPET
  - WHITE_CARPET
blacklisted-chairs: []
disabled-worlds: []